import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import SystemIdentifierIcon from './SystemIdentifierIcon';

const meta = {
  title: 'Icons/System/SystemIdentifierIcon',
  component: SystemIdentifierIcon,
  parameters: {
    layout: 'centered',
  },
  tags: ['autodocs'],
  argTypes: {
    size: {
      control: 'select',
      options: ['sm', 'md', 'lg'],
      description: 'Size of the icon',
    },
    className: {
      control: 'text',
      description: 'Additional CSS classes for styling',
    },
  },
} satisfies Meta<typeof SystemIdentifierIcon>;

export default meta;
type Story = StoryObj<typeof meta>;

/**
 * Default System Identifier Icon
 * Shows the auto-generated system identifier icon in medium size
 */
export const Default: Story = {
  args: {
    size: 'md',
  },
};

/**
 * Small System Identifier Icon
 * Useful for inline usage or compact layouts
 */
export const Small: Story = {
  args: {
    size: 'sm',
  },
};

/**
 * Large System Identifier Icon
 * Suitable for prominently featured identifiers
 */
export const Large: Story = {
  args: {
    size: 'lg',
  },
};

/**
 * System Identifier Icon with Custom Color
 * Demonstrates styling with custom color classes
 */
export const WithCustomColor: Story = {
  args: {
    size: 'md',
    className: 'text-blue-600',
  },
};

/**
 * System Identifier Icon - Primary Color
 */
export const PrimaryColor: Story = {
  args: {
    size: 'md',
    className: 'text-blue-500',
  },
};

/**
 * System Identifier Icon - Success Color
 */
export const SuccessColor: Story = {
  args: {
    size: 'md',
    className: 'text-green-500',
  },
};

/**
 * System Identifier Icon - Warning Color
 */
export const WarningColor: Story = {
  args: {
    size: 'md',
    className: 'text-amber-500',
  },
};

/**
 * System Identifier Icon - All Sizes with Colors
 * Complete showcase of all available sizes with custom styling
 */
export const AllSizes: Story = {
  render: () => (
    <div className="flex items-center gap-8">
      <div className="flex flex-col items-center gap-2">
        <SystemIdentifierIcon size="sm" className="text-blue-500" />
        <span className="text-sm text-gray-600">Small</span>
      </div>
      <div className="flex flex-col items-center gap-2">
        <SystemIdentifierIcon size="md" className="text-blue-600" />
        <span className="text-sm text-gray-600">Medium</span>
      </div>
      <div className="flex flex-col items-center gap-2">
        <SystemIdentifierIcon size="lg" className="text-blue-700" />
        <span className="text-sm text-gray-600">Large</span>
      </div>
    </div>
  ),
};

/**
 * System Identifier Icon - Usage Example
 * Shows how the icon might be used in a real application context
 */
export const UsageExample: Story = {
  render: () => (
    <div className="flex items-center gap-3 p-4 bg-blue-50 rounded-lg border border-blue-200 w-full max-w-md">
      <SystemIdentifierIcon size="md" className="text-blue-600 flex-shrink-0" />
      <div className="flex-1">
        <h3 className="text-sm font-semibold text-gray-900">System Identifier</h3>
        <p className="text-xs text-gray-500">Auto-generated by the system</p>
        <p className="text-sm font-mono text-blue-700 mt-1">03112025-001</p>
      </div>
    </div>
  ),
};
